run:
  deadline: 30m
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
    ignore-words:
      - vell

linters:
  enable:
    - deadcode
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - interfacer
    - maligned
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
